config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "welcome#index"

  resources :entries
  resources :entry_comments
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admin_users_on_email                 (email) UNIQUE
#  index_admin_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :entry_comments

  default_scope { order(created_at: :desc) }

  validates :title, presence: true
  validates :summary, presence: true
  validates :body, presence: true
end

# == Schema Information
#
# Table name: entries
#
#  id         :integer          not null, primary key
#  title      :string
#  summary    :text
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/entry_comment.rb
class EntryComment < ApplicationRecord
  belongs_to :entry

  validates :author, presence: true
  validates :body, presence: true
end

# == Schema Information
#
# Table name: entry_comments
#
#  id         :integer          not null, primary key
#  author     :string
#  body       :text
#  entry_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_entry_comments_on_entry_id  (entry_id)
#
# Foreign Keys
#
#  fk_rails_...  (entry_id => entries.id)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: :show

  def index
    @entries = Entry.all.includes(:entry_comments).page(params[:page])
  end

  def show
    @entry
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end
end

app/controllers/entry_comments_controller.rb
class EntryCommentsController < ApplicationController
  def new
    @entry_comment = EntryComment.new
  end

  def create
    @entry_comment = EntryComment.create!(entry_comments_params)
    redirect_to @entry_comment.entry
  end

  private

  def entry_comments_params
    params[:comment_entry].permit(:author, :body, :entry_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @last_news = Entry.first(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entry_comments_helper.rb
module EntryCommentsHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Fake News</h1>
      <% @entries.each do |entry| %>
      <h2><%= link_to entry.title, entry_path(entry) %></h2>
      <p><%= link_to entry.summary.truncate(200), entry_path(entry) %></p>
      <p><%= link_to entry.body.truncate(500), entry_path(entry) %></p>
      <p><%= link_to "#{entry.entry_comments.count} comments.", entry_path(entry) %></p>
      <hr>
      <% end %>

      <%= paginate @entries %>
      <%= link_to "Back", root_path %>
    </div>
  </div>
</div>

app/views/entries/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @entry.title %></h1>
      <h4><%= @entry.summary %></h4>
      <p><%= @entry.body %></p>
      <hr>
      <%= form_for :comment_entry, url: entry_comments_path, class: "input-group mb-3" do |f| %>
      Name: <%= f.text_field :author, class: "form-control" %><br />
      <%= f.text_area :body, class: "form-control" %><br />
      <%= f.hidden_field :entry_id, value: @entry.id %>
      <%= f.submit "Coment" %>
      <% end %>
      <hr>
      <% @entry.entry_comments.each do |comment| %>
      <p><%= comment.author %>:</p>
      <p><%= comment.body %></p>
      <hr>
      <% end %>

      <%= link_to "Back", root_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Fake News</h1>
      <nav class="nav">
        <%= link_to "Admin", admin_dashboard_path, class: "nav-link" %>
        <%= link_to "All", entries_path, class: "nav-link" %>
      </nav>
      <hr>

      <% @last_news.each do |entry| %>
      <h2><%= link_to entry.title, entry_path(entry) %></h2>
      <p><%= link_to entry.summary.truncate(200), entry_path(entry) %></p>
      <p><%= link_to entry.body.truncate(500), entry_path(entry) %></p>
      <p><%= link_to "#{entry.entry_comments.count} comments.", entry_path(entry) %></p>
      <hr>
      <% end %>

    </div>
  </div>
</div>